### ISSUE TITLE
Wrong repos for edge clusters example

### ISSUE THREAD

**Issue by e-minguez** [suse-edge/misc#89]
https://github.com/suse-edge/misc/blob/a3609056024636443e74a1ee24b53189568f3d72/telco-examples/edge-clusters/dhcp-less/edge-metallb-multi-node/telco-capi-metallb-multi-node.yaml#L120

It should be charts instead.

Same for the endpoint copier operator.

Also the targetNamespaces should be different (in fact, metallb will complain about this IIRC as there is a webhook that prevents ipaddresspool on other namespaces than the metallb-system)

Something like this:

```
        storage:
          files:
            - path: /var/metallb-endpointcopier-operators.yaml
              overwrite: true
              contents:
                inline: |
                  apiVersion: helm.cattle.io/v1
                  kind: HelmChart
                  metadata:
                    name: metallb
                    namespace: kube-system
                  spec:
                    repo: https://suse-edge.github.io/charts
                    chart: metallb
                    targetNamespace: metallb-system
                    version: 0.14.3
                    createNamespace: true
                  ---
                  apiVersion: helm.cattle.io/v1
                  kind: HelmChart
                  metadata:
                    name: endpoint-copier-operator
                    namespace: kube-system
                  spec:
                    repo: https://suse-edge.github.io/charts
                    chart: endpoint-copier-operator
                    targetNamespace: endpoint-copier-operator
                    version: 0.2.0
                    createNamespace: true
            - path: /var/metallb-cr.yaml
              overwrite: true
              contents:
                inline: |
                  apiVersion: metallb.io/v1beta1
                  kind: IPAddressPool
                  metadata:
                    name: kubernetes-vip-ip-pool
                    namespace: metallb-system
                  spec:
                    addresses:
                      - 10.85.17.9/32
                    serviceAllocation:
                      priority: 100
                      namespaces:
                        - default
                  ---
                  apiVersion: metallb.io/v1beta1
                  kind: L2Advertisement
                  metadata:
                    name: ip-pool-l2-adv
                    namespace: metallb-system
                  spec:
                    ipAddressPools:
                      - kubernetes-vip-ip-pool
```
